### PR TITLE
Require project and user names

### LINKED ISSUE #42: Validate user input
Trying to create a project without a name leads to an error page, as the database field is marked as `NOT NULL`. Instead, validate the input and bounce back to the edit page with the incorrect field(s) highlighted.

Thanks to @ihross for discovering this!

### PR DESCRIPTION
**Pull request by jasonaowen**
Validate the input sent to the server to make sure that the user's public and internal names are present and not empty, and to make sure that the project's name is present and not empty.

Mark the fields as [`required`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-required) in the HTML so that the browser will help us out.

Thank you @kiddspazz for pairing with me on this!

Screenshot 2019-05-01 17:33:39
Screenshot 2019-05-01 17:32:55

Resolves #42 Validate user input

### CODE REVIEW

File: src/main/java/com/recurse/portfolio/web/UserController.java [hunk 1]
```diff
@@ -118,10 +122,29 @@ public RedirectView postEditMyProfile(
...
-        return new RedirectView("/user/" + userId);
+    private List<String> validate(User postedUser) {
+        List<String> errors = new ArrayList<>();
+        if (StringUtils.isEmpty(postedUser.getPublicName())) {
+            errors.add("publicName");
+        }
+        if (StringUtils.isEmpty(postedUser.getInternalName())) {
+            errors.add("internalName");
+        }
+        return errors;
```
Comment (jasonaowen) [inline src/main/java/com/recurse/portfolio/web/UserController.java]: It turns out [Spring supports form input validation natively](https://spring.io/guides/gs/validating-form-input/), so that we don't have to write this `validate` method in each controller. I'll work on adding that.
